// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RazorPages_IMDB.Models
{
    public partial class Genre
    {
        public Genre()
        {
            TitleGenres = new HashSet<TitleGenre>();
        }

        [Key]
        [Column("genreId")]
        public int GenreId { get; set; }
        [Required]
        [Column("genre")]
        [StringLength(50)]
        [Unicode(false)]
        public string Genre1 { get; set; }

        [InverseProperty("Genre")]
        public virtual ICollection<TitleGenre> TitleGenres { get; set; }
    }
}