// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RazorPages_IMDB.Models
{
    public partial class NamePrimaryProfession
    {
        [Key]
        public int NamePrimaryProfessionId { get; set; }
        [Column("nconst")]
        [StringLength(50)]
        [Unicode(false)]
        public string Nconst { get; set; }
        public int? PrimaryProfessionId { get; set; }

        [ForeignKey("Nconst")]
        [InverseProperty("NamePrimaryProfessions")]
        public virtual Name NconstNavigation { get; set; }
        [ForeignKey("PrimaryProfessionId")]
        [InverseProperty("NamePrimaryProfessions")]
        public virtual PrimaryProfession PrimaryProfession { get; set; }
    }
}