// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RazorPages_IMDB.Models
{
    public partial class NameKnownForTitle
    {
        [Key]
        public int NameKnownForTitlesId { get; set; }
        [Column("nconst")]
        [StringLength(50)]
        [Unicode(false)]
        public string Nconst { get; set; }
        [Column("tconst")]
        [StringLength(50)]
        [Unicode(false)]
        public string Tconst { get; set; }

        [ForeignKey("Nconst")]
        [InverseProperty("NameKnownForTitles")]
        public virtual Name NconstNavigation { get; set; }
        [ForeignKey("Tconst")]
        [InverseProperty("NameKnownForTitles")]
        public virtual Title TconstNavigation { get; set; }
    }
}