// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RazorPages_IMDB.Models
{
    public partial class TitleType
    {
        public TitleType()
        {
            Titles = new HashSet<Title>();
        }

        [Key]
        [Column("titleTypeId")]
        public int TitleTypeId { get; set; }
        [Required]
        [Column("titleType")]
        [StringLength(50)]
        [Unicode(false)]
        public string TitleType1 { get; set; }

        [InverseProperty("TitleType")]
        public virtual ICollection<Title> Titles { get; set; }
    }
}