// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RazorPages_IMDB.Models
{
    public partial class WriterForTitle
    {
        [Key]
        public int WriterForTitlesId { get; set; }
        [Column("tconst")]
        [StringLength(50)]
        [Unicode(false)]
        public string Tconst { get; set; }
        [Column("nconst")]
        [StringLength(50)]
        [Unicode(false)]
        public string Nconst { get; set; }

        [ForeignKey("Nconst")]
        [InverseProperty("WriterForTitles")]
        public virtual Name NconstNavigation { get; set; }
        [ForeignKey("Tconst")]
        [InverseProperty("WriterForTitles")]
        public virtual Title TconstNavigation { get; set; }
    }
}